name : pems_vmp2
model : bayesian2_80_ep52.pt
# bayesian2_80_ep52.pt deterministic2_ep21.pt
# load existing weights from ./models/[name]/[model]
load : True
# partial load (e.g., to initialize deterministic weights)
partial : False
# Training or inference
train : False
seed : 42
gpu_number : ~
# Use wandb
wandb : False

# model

# use transformer or lstm
transfo : True
# nb of multi-head (n), nb of heads per multi-head (h)
dim : [2, 9]
# use embedding layers
embed : False
# embedding dimensions, if embed: we must have emb[-1]%h = 0, else: we must have input_dim%h=0
emb : ~
# classifiers dimensions, we must have emb[-1] = clas[0]
clas : [963,]
# use uncertainty quantification
vmp : True
# residual connection mode for variance computation : identity, independence, taylor
residual : independence

# training

epochs : ~
batch_size : 32
optimizer : sgd
learning_rate : 1.e-3
# End factor to multiply the learning rate at the last epoch
end_factor : 1.e-1
l2_reg : 0.
# l2 regularization hyperparameter in ELBO
kl_factor : 1.e-7
# gradient clipping
clip : 10
# nb of workers for dataloaders
workers : 4
# tolerance in (0, 1) for avoiding nan in log(), 1/, sqrt()
tol : 1.e-9
# initialization bounds for variance 
var_init : [1.e-3, 1.e-2]

# testing

# clean or gaussian
noise : gaussian
# start (included), stop (excluded), step
level   : [-50, 21, 10]
# [0.01, 5.1, 0.5]
# if true: level is snr. If false: level is noise std.
snr : True
# print a few predictions along their variance
sample : True


# dataset

dataset : pems
# input dimension
input_dim : 963
# input sequence length
t_in : 144
# output dimension
output_dim : 7
# output sequence length
t_out : ~
